Feature/create qs
Wavemind/medal-creator pull request #113
Opened 2023-05-16 12:30 UTC by ManuBarchich

2023-05-17 13:43 UTC, cini9 approved these changes

2023-05-30 12:51 UTC, frescoal requested changes
Dans tous les type vérifier que ceux qui sont toujours remplis aient :  ", null: false"

2023-05-30 12:51 UTC, frescoal commented on api/app/graphql/types/questions_sequence_type.rb
> +    field :type, String
Définir comme non null

2023-05-30 12:51 UTC, frescoal commented on api/app/graphql/types/questions_sequence_type.rb
>      field :cut_off_end, Integer
Answer peut pas être null il me semble

2023-05-30 12:51 UTC, frescoal commented on api/app/graphql/types/variable_type.rb
> +    field :type, String
Définir pour tous les champs lesquels sont toujours remplis

2023-05-30 12:51 UTC, frescoal commented on api/app/graphql/types/input/questions_sequence_input_type.rb
> +      argument :type, String, required: false
required true nan ?

2023-05-30 12:51 UTC, frescoal commented on api/app/graphql/mutations/questions_sequences/create_questions_sequence.rb
> +
Class name devrait être QuestionSequence ou node mais pas Projet

2023-05-30 12:51 UTC, frescoal commented on api/app/graphql/types/input/variable_input_type.rb
> +      argument :type, String, required: false
Vérifier les requireds

2023-05-30 12:51 UTC, frescoal commented on api/app/graphql/mutations/variables/create_variable.rb
> +        context[:current_api_v1_user] = User.first
To Delete

2023-05-30 12:51 UTC, frescoal commented on api/app/graphql/mutations/variables/create_variable.rb
> +        raise GraphQL::ExecutionError, I18n.t('graphql.errors.wrong_access', class_name: 'Project')
Change class_name

2023-05-30 12:51 UTC, frescoal commented on api/config/locales/fr.yml
> +        minimum_age: "Minimum age for consultation (in days)"
Translate

2023-05-30 12:51 UTC, frescoal commented on api/spec/graphql/mutations/questions_sequences/create_questions_sequence_spec.rb
> +          result = ''
why ? si elle est attribuée juste en dessous ?

2023-05-30 12:51 UTC, frescoal commented on api/spec/graphql/mutations/variables/create_variable_spec.rb
> +          params['answersAttributes'] = [
why not in a factory ?

2023-05-30 12:51 UTC, frescoal commented on api/spec/graphql/mutations/variables/create_variable_spec.rb
> +          result = RailsGraphqlSchema.execute(query, variables: wrong_variables, context: context)
Test si le nombre d'image a été augmenté

2023-05-31 11:48 UTC, ManuBarchich commented on api/app/graphql/mutations/questions_sequences/create_questions_sequence.rb
> +
Non, c'est bien au niveau du projet que les accès sont liés

2023-05-31 11:49 UTC, ManuBarchich commented on api/spec/graphql/mutations/questions_sequences/create_questions_sequence_spec.rb
> +          result = ''
La valeur étant attribuée dans un block, je dois la déclarer avant

2023-05-31 11:50 UTC, ManuBarchich commented on api/spec/graphql/mutations/variables/create_variable_spec.rb
> +          result = RailsGraphqlSchema.execute(query, variables: wrong_variables, context: context)
Il doit pas y avoir d'images puisque je teste un crash

2023-06-01 14:19 UTC, merged