Feature/failing tests
Wavemind/medal-creator pull request #114
Opened 2023-05-16 12:56 UTC by ManuBarchich

2023-05-16 13:16 UTC, quentingirard approved these changes

2023-05-30 08:58 UTC, frescoal requested changes
Ajouter les test quand l'id est erroné exemple on cherche un Algorithm qui existe pas vérifier qu'on a un 404 ou équvalents Même chose pour les termes de recherche quand il n'y a pas de résultats trouvés

2023-05-30 08:58 UTC, frescoal commented on api/app/models/algorithm.rb
> +  validates :age_limit, numericality: { greater_than: 0 }
why ?

2023-05-31 12:53 UTC, ManuBarchich commented on api/app/models/algorithm.rb
> +  validates :age_limit, numericality: { greater_than: 0 }
Ca veut dire la même chose en plus propre

2023-06-05 11:51 UTC, merged