Feature/question form
Wavemind/medal-creator pull request #119
Opened 2023-05-30 09:52 UTC by cini9

2023-05-30 15:56 UTC, cini9 reviewed
Est-ce qu'on updaterai pas ts target a es6 dans tsconfig aussi ? Je sais pas si ca va changer grand chose, mais au moins on est a jour ?

2023-05-30 15:56 UTC, cini9 commented on front/components/forms/answers.tsx
> +  const handleAppend = () => append({ isUnavailable: false })
Est-ce qu'on devrait ajouter label vu qu'il est present dans tous les cas ?

2023-05-30 15:56 UTC, cini9 commented on front/components/forms/variable.tsx
> +  // TODO: IMPROVE
Toujours d'actualité ?

2023-05-30 15:56 UTC, cini9 commented on front/components/forms/variable.tsx
> +    if (
Find a way to improve this if, or another way to make typescript happy

2023-05-30 15:56 UTC, cini9 commented on front/components/forms/variableStepper.tsx
> +  // Check if here or in variable.ts
Toujours d'actualité ?

2023-05-30 15:56 UTC, cini9 commented on front/components/forms/variableStepper.tsx
> +  // TODO: MAKE THIS WORK
Toujours d'actualité ?

2023-05-30 15:56 UTC, cini9 commented on front/components/forms/variableStepper.tsx
> +  useEffect(remove, [watchAnswerType])
Pas besoin du callback ici ? ( () => ...)

2023-05-30 15:56 UTC, cini9 commented on front/components/forms/variableStepper.tsx
> +            console.log('isOverlapValid', isOverlapValid)
💩

2023-05-30 15:56 UTC, cini9 commented on front/components/forms/variableStepper.tsx
> +            console.log('message', message)
💩

2023-05-30 15:56 UTC, cini9 commented on front/components/forms/variableStepper.tsx
> +    // TODO ADD updateMode && (is_used || is_deployed)
Toujours d'actualité ?

2023-05-30 15:56 UTC, cini9 commented on front/components/forms/variableStepper.tsx
> +  return <Spinner />
size='xl' ?

2023-05-30 15:56 UTC, cini9 commented on front/components/inputs/input.tsx
> +import { ErrorMessage } from '@hookform/error-message'
Put these two in the external imports

2023-05-30 15:56 UTC, cini9 commented on front/components/modal/variableInstances.tsx
> -  return <Spinner />
Si il est toujours xl, peut etre faire un override general dans theme ?

2023-05-30 15:56 UTC, cini9 commented on front/lib/api/modules/node.ts
> +// TODO MIGRATE IT IN VARIABLE
Toujours d'actualité ?

2023-05-30 15:56 UTC, cini9 commented on front/lib/config/constants.ts
> +// TODO: CLEAR These constants and improve it
Toujours d'actualité ?

2023-05-30 15:56 UTC, cini9 commented on front/lib/services/variable.service.ts
> +    console.log({
💩

2023-05-31 08:15 UTC, quentingirard requested changes

2023-05-31 08:15 UTC, quentingirard commented on front/components/answerLine.tsx
> +  const operators = useMemo(() => {
commentaire

2023-05-31 08:15 UTC, quentingirard commented on front/components/forms/answers.tsx
> +  const handleAppend = () => append({ isUnavailable: false })
on peut oui

2023-05-31 08:15 UTC, quentingirard commented on front/components/forms/answers.tsx
> +  const error = useMemo(() => {
commentaire

2023-05-31 08:15 UTC, quentingirard commented on front/components/forms/variable.tsx
> +  // TODO: IMPROVE
A supprimer

2023-05-31 08:15 UTC, quentingirard commented on front/components/forms/variable.tsx
> +  const canDisplayUnavailableOption = useMemo(
ajouter des commentaires

2023-05-31 08:15 UTC, quentingirard commented on front/components/forms/variableStepper.tsx
> +  // Check if here or in variable.ts
Commentaire à supprimer

2023-05-31 08:15 UTC, quentingirard commented on front/components/forms/variableStepper.tsx
> +  // TODO: MAKE THIS WORK
Commentaire à supprimer

2023-05-31 08:15 UTC, quentingirard commented on front/components/forms/variableStepper.tsx
> +  useEffect(remove, [watchAnswerType])
Effectivement pas besoin car c'est une methodes sans paramètre. Comme dans un onClick

2023-05-31 08:15 UTC, quentingirard commented on front/components/forms/variableStepper.tsx
> +    // TODO ADD updateMode && (is_used || is_deployed)
Oui toujours en attendant la gestion de draft/production des algorithmes

2023-05-31 08:15 UTC, quentingirard commented on front/lib/services/variable.service.ts
> +  public validateOverlap(answers: AnswerInputs[] | undefined): {
comment

2023-05-31 08:15 UTC, quentingirard commented on front/types/variable.d.ts
> +// TODO: FIX IT
remove it

2023-05-31 08:15 UTC, quentingirard commented on front/types/variable.d.ts
> +// TODO: Add info here
remove

2023-06-01 15:09 UTC, merged