Feature/conditions
Wavemind/medal-creator pull request #150
Opened 2023-07-18 11:50 UTC by ManuBarchich

2023-07-19 07:37 UTC, cini9 requested changes
Manque juste les specs pour update_condition et get_condition et faut le pointer sur feature/diagram

2023-07-20 08:14 UTC, frescoal requested changes

2023-07-20 08:14 UTC, frescoal commented on api/app/graphql/mutations/conditions/create_condition.rb
> +          condition = Condition.new(condition_params)
pourquoi tu fais pas directement un condition create dans la condition  ?

2023-07-20 08:14 UTC, frescoal commented on api/db/seeds.rb
Why ?

2023-07-20 08:14 UTC, frescoal commented on api/spec/graphql/mutations/conditions/destroy_condition_spec.rb
> +      end
SI on essaie de supprimer un id qui existe pas ?

2023-07-20 08:14 UTC, frescoal commented on api/spec/graphql/mutations/conditions/create_condition_spec.rb
> +
Tu as pris en comptes le cut off sur les conditions ?

2023-07-20 08:55 UTC, ManuBarchich commented on api/spec/graphql/mutations/conditions/create_condition_spec.rb
> +
Pas de cut offs à la création

2023-07-20 08:58 UTC, ManuBarchich commented on api/db/seeds.rb
Why what ?

2023-07-20 08:58 UTC, ManuBarchich commented on api/app/graphql/mutations/conditions/create_condition.rb
> +          condition = Condition.new(condition_params)
Comment ça ?

2023-07-21 11:34 UTC, frescoal commented on api/app/graphql/mutations/conditions/create_condition.rb
> +          condition = Condition.new(condition_params)
if Condition.create!(condition_params)

2023-07-21 11:35 UTC, frescoal commented on api/db/seeds.rb
pourquoi tu as enlevé le !

2023-07-21 11:35 UTC, frescoal commented on api/spec/graphql/mutations/conditions/create_condition_spec.rb
> +
k

2023-07-21 11:52 UTC, ManuBarchich commented on api/app/graphql/mutations/conditions/create_condition.rb
> +          condition = Condition.new(condition_params)
Pour pouvoir instancier condition et le renvoyer, c'est standard CRUD rails ça

2023-07-21 11:53 UTC, ManuBarchich commented on api/db/seeds.rb
Aaah, le why était sur le "next if". J'ai enlevé parce que dans les old data il y avait des doublons de Condition. Mais vue que maintenant on a un validate uniquness, ils font planter les seeds. J'ai enlevé le ! pour que les doublons ne soient pas créés mais que les seeds continuent après

2023-07-21 12:12 UTC, closed without merging