Fix/diagram instances
Wavemind/medal-creator pull request #156
Opened 2023-07-24 15:07 UTC by quentingirard

2023-07-24 15:20 UTC, cini9 requested changes

2023-07-24 15:20 UTC, cini9 commented on front/components/diagram/node/ui/nodeHeader.tsx
> +import { FormEnvironments } from '@/lib/config/constants'
Mettre le type import a la fin

2023-07-24 15:20 UTC, cini9 commented on front/components/forms/variableStepper.tsx
> +  FormEnvironments,
Do you use this import ?

2023-07-24 15:20 UTC, cini9 commented on front/components/inputs/variable/category.tsx
> +import { VariableCategoryEnum } from '@/types'
Mettre le type import a la fin

2023-07-24 15:20 UTC, cini9 commented on front/components/inputs/variable/category.tsx
> +const Category: CategoryComponent = ({ isDisabled, formEnvironment }) => {
Pas moyen d'obtenir cette info depuis le router (par ex instanceableType) au lieu de le passer a travers tous les composants ?

2023-07-24 15:20 UTC, cini9 commented on front/pages/projects/[projectId]/library/index.tsx
> +import { FormEnvironments } from '@/lib/config/constants'
Mettre le type import a la fin

2023-07-24 15:20 UTC, cini9 commented on front/pages/projects/[projectId]/library/index.tsx
> +          formEnvironment={FormEnvironments.Default}
Si tu ne peux pas obtenir l'info directement dans le composant Category, on peut mettre FormEnvironments.Default comme valeur par default dans VariableStepper ?

2023-07-24 15:20 UTC, cini9 commented on front/pages/projects/[projectId]/library/index.tsx
> +          formEnvironment={FormEnvironments.Default}
Si oui pour commentaire en dessus, enlever ici

2023-07-25 06:23 UTC, quentingirard commented on front/pages/projects/[projectId]/library/index.tsx
> +import { FormEnvironments } from '@/lib/config/constants'
nope, c'est un enum

2023-07-25 06:28 UTC, quentingirard commented on front/components/inputs/variable/category.tsx
> +import { VariableCategoryEnum } from '@/types'
nope, c'est un enum

2023-07-25 14:37 UTC, merged