Feature/download variables
Wavemind/medal-creator pull request #207
Opened 2023-09-27 13:06 UTC by quentingirard

2023-09-28 07:23 UTC, frescoal requested changes

2023-09-28 07:23 UTC, frescoal commented on api/app/services/export_translations_service.rb
> +    "#{Rails.application.routes.default_url_options[:host]}/exports/#{xl_hash}.xlsx"
Est-ce que ça veut dire que à chaque fois qu'on génère un fichier il est stocker sur le serveur pour toujours ?

2023-09-28 07:23 UTC, frescoal commented on api/app/services/export_variables_service.rb
> +    "#{Rails.application.routes.default_url_options[:host]}/exports/#{xl_hash}.xlsx"
Est-ce que ça veut dire que à chaque fois qu'on génère un fichier il est stocker sur le serveur pour toujours ?

2023-09-28 07:23 UTC, frescoal commented on front/components/sidebar/subMenu.tsx
> +          Download variables
Heuuu

2023-09-28 07:48 UTC, cini9 requested changes

2023-09-28 07:48 UTC, cini9 commented on front/components/sidebar/subMenu.tsx
> +    if (response.data && response.data.url) {
Pourquoi tu optes pour un await ici plutot qu'un useEffect avec onSuccess comme on fait un peu partout ? En plus dans algorithm.enhanced tu transform le response.

2023-10-09 14:09 UTC, frescoal requested changes

2023-10-09 14:09 UTC, frescoal commented on api/app/services/export_variables_service.rb
> +
Est-ce que les fichiers sont automatiquement effacé sur le s3 ? Si oui après combien de temps ?

2023-10-10 12:03 UTC, merged