Feature/diagnosis diagram
Wavemind/medal-creator pull request #227
Opened 2023-11-21 13:06 UTC by quentingirard

2023-11-21 16:07 UTC, cini9 requested changes

2023-11-21 16:07 UTC, cini9 commented on front/components/diagram/header/wrapper.tsx
> +        return <DecisionTreeHeader />
Peut etre renommer les composants en DecisionTreeBreadcrumbs et DiagnosisBreadcrumbs, vu que tu les sauves dans une variables breadcrumbs ?

2023-11-21 16:07 UTC, cini9 commented on front/components/diagram/header/wrapper.tsx
> +  }, [instanceableId])
pourquoi il depend de instanceableId ?

2023-11-21 16:07 UTC, cini9 commented on front/components/diagram/header/wrapper.tsx
> +          aria-label='close'
trad ?

2023-11-21 16:07 UTC, cini9 commented on front/components/diagram/index.tsx
> +  const { generateInstance, diagramType } = useDiagram()
Je pense qu'on peut aussi passer a travers les fichiers et regrouper / standardiser l'ordre des hooks. Genre, d'abord les translations, ensuite les state, etc. Si t'es d'accord, mets un TODO ?

2023-11-21 16:07 UTC, cini9 commented on front/components/diagram/node/drug.tsx
> +import { memo } from 'react'
Regrouper les imports, il faut economiser les lignes de code

2023-11-21 16:07 UTC, cini9 commented on front/components/diagram/node/drug.tsx
> +      <Box>
The flex inside of the box feels superflu. On a besoin du box ?

2023-11-21 16:07 UTC, cini9 commented on front/components/diagram/node/management.tsx
> +      <Box>
same ?

2023-11-21 16:07 UTC, cini9 commented on front/components/diagram/node/ui/nodeHeaderMenu.tsx
> +            title: t('new', { ns: 'questionsSequence' }),
Le titre doit bien etre "new" ?

2023-11-21 16:07 UTC, cini9 commented on front/components/diagram/nodeFilter.tsx
> +const NodeFilter = () => {
Je crois qu'il faut quand meme garder le FC pour que le composant soit typé

2023-11-21 16:07 UTC, cini9 commented on front/components/forms/drugStepper.tsx
> +    const nodeToReturn = updatedDrug || newDrug
Qu'est ce qui se passe si tu crées un drug apres avoir updaté un autre drug ? Est-ce que le cache de RTK garde le updatedDrug, et tu appelles ton callback avec le mauvais drugToReturn ?

2023-11-21 16:07 UTC, cini9 commented on front/components/forms/instance.tsx
> +  const { close: closeModal } = useModal()
Est-ce qu'on renommerai pas close en closeModal dans le provider pour ne pas devoir faire ca a chaque fois ?

2023-11-21 16:07 UTC, cini9 commented on front/components/forms/instance.tsx
> +    const nodeToReturn = newInstance || updatedInstance
Same commentaire que dans drugStepper ?

2023-11-21 16:07 UTC, cini9 commented on front/components/forms/management.tsx
> +    const nodeToReturn = updatedManagement || newManagement
same ?

2023-11-21 16:07 UTC, cini9 commented on front/components/table/decisionTreeRow.tsx
> +import { extractTranslation } from '@/lib/utils/string'
Mettre en dessus des type import

2023-11-21 16:07 UTC, cini9 commented on front/components/table/menuCell.tsx
> -  // TODO: Improvement needed for tooltip and message. Wait role
Improvement not needed anymore ?

2023-11-21 16:07 UTC, cini9 commented on api/app/graphql/types/diagnosis_type.rb
> +    field :decision_tree_id, ID, null: false
Besoin des 2 ? On peut pas juste acceder au decision_tree_id a travers decision_tree en dessus ?

2023-11-21 16:07 UTC, cini9 commented on front/lib/api/modules/documents/diagnosis.graphql
> +    decisionTreeId
Check comment in diagnosis_type

2023-11-21 16:07 UTC, cini9 commented on front/pages/projects/[projectId]/diagram/[instanceableType]/[instanceableId]/index.tsx
> +    if (isGetDecisionTreeSuccess) {
Meme commentaire avec le cache de RTK

2023-11-27 10:14 UTC, cini9 requested changes

2023-11-27 10:14 UTC, cini9 commented on front/components/diagram/node/drug.tsx
> +      <Flex
Mettre ce Flex dans le NodeWrapper aussi ? Il me semble que c'est commun entre tous les nodes ?

2023-11-27 10:14 UTC, cini9 commented on front/components/inputs/variable/category.tsx
> +  const isDecisionTreeDiagram = formEnvironment === DiagramEnum.DecisionTree
useMemo pour ne pas recalculer a chaque render ?

2023-11-27 10:14 UTC, cini9 commented on front/lib/providers/diagram.tsx
> +  // TODO: RENAME IT
Toujours d'actualité ?

2023-11-27 10:16 UTC, qtn-g commented on front/components/diagram/node/drug.tsx
> +      <Flex
Non ça ne l'est pas malheureusement

2023-11-27 10:17 UTC, qtn-g commented on front/components/inputs/variable/category.tsx
> +  const isDecisionTreeDiagram = formEnvironment === DiagramEnum.DecisionTree
le useMemo va utiliser plus de mémoire que de tester un boolean

2023-11-27 14:37 UTC, merged