Feature/qs diagram
Wavemind/medal-creator pull request #235
Opened 2023-12-04 14:52 UTC by cini9

2023-12-04 16:05 UTC, quentingirard requested changes

2023-12-04 16:05 UTC, qtn-g commented on front/components/diagram/edge/scoreEdge.tsx
> +    <>
Est-ce qu'on ferait pas un edgeWrapper avec les fonctions/styles similaire aux autres edges ?

2023-12-04 16:05 UTC, qtn-g commented on front/components/forms/score.tsx
> +        error={updateConditionError}
Pourquoi tu utilises pas le isSuccess props avec le callback intégré ?

2023-12-04 16:05 UTC, quentingirard commented on front/types/component.d.ts
> +  minScore?: number | null | undefined
undefined inutile vu qu'il y a ?

2023-12-04 16:05 UTC, quentingirard commented on front/types/component.d.ts
> +  minScore: number | null
Pourquoi ne pas avoir mis minScore en optionnel aussi ?

2023-12-05 08:24 UTC, cini9 commented on front/components/diagram/edge/scoreEdge.tsx
> +    <>
We can't

2023-12-06 14:31 UTC, merged