Feature/duplication
Wavemind/medal-creator pull request #244
Opened 2023-12-14 15:05 UTC by cini9

2023-12-14 16:11 UTC, quentingirard requested changes

2023-12-14 16:11 UTC, qtn-g commented on api/app/models/instance.rb
> +  # validates :duration_translations, translated_fields_presence: { project: lambda { |record|
?

2023-12-14 16:11 UTC, qtn-g commented on api/app/services/duplicate_algorithm_service.rb
> +        puts "############################################################"
remove

2023-12-14 16:11 UTC, qtn-g commented on api/app/services/duplicate_algorithm_service.rb
> +        # Algorithm.validate_duplicate(self, new_algorithm)
Why is it commented ?

2023-12-14 16:11 UTC, qtn-g commented on api/app/services/duplicate_algorithm_service.rb
> +                    .merge({'name': "Copy of #{@algorithm.name}", 'status': 'draft'}))
Translate it with the project default language

2023-12-14 16:11 UTC, quentingirard commented on front/components/duplicate.tsx
> +import { DuplicateComponent } from '@/types'
type

2023-12-14 16:11 UTC, quentingirard commented on front/components/duplicate.tsx
> +        message: t('notifications.archiveError', { ns: 'common' }),
update messages

2023-12-14 16:11 UTC, quentingirard commented on front/components/duplicate.tsx
> +   * Queue toast if error during destruction
remove or change it

2023-12-14 16:11 UTC, quentingirard commented on front/components/duplicate.tsx
> +                  <HStack justifyContent='space-between' w='full'>
🤦

2023-12-14 16:11 UTC, quentingirard commented on front/lib/hooks/useChannel.ts
> +      console.log('Requesting current job info')
remove

2023-12-14 16:11 UTC, quentingirard commented on front/pages/projects/[projectId]/algorithms/index.tsx
>          message: t('notifications.archiveError', { ns: 'common' }),
wrong translations

2023-12-14 16:11 UTC, quentingirard commented on front/pages/projects/[projectId]/algorithms/index.tsx
> +                row.status !== 'archived' ? () => onArchive(row.id) : undefined
use algoritm status enum

2023-12-14 16:11 UTC, quentingirard commented on front/types/component.d.ts
> +  setIsDuplicating: React.Dispatch<React.SetStateAction<boolean>>
React is missing in external imports

2023-12-14 16:16 UTC, cini9 commented on api/app/models/instance.rb
> +  # validates :duration_translations, translated_fields_presence: { project: lambda { |record|
@ManuBarchich ?

2023-12-14 16:24 UTC, cini9 commented on front/components/duplicate.tsx
> +                  <HStack justifyContent='space-between' w='full'>
🤫

2023-12-15 09:23 UTC, frescoal requested changes
Les tests passent pas

2023-12-15 09:23 UTC, frescoal commented on api/app/graphql/mutations/algorithms/duplicate_algorithm.rb
> +          DuplicateAlgorithmJob.perform_now(id)
Perform_later nan ?

2023-12-15 09:23 UTC, frescoal commented on front/components/publish.tsx
> +  const isSingleValue = (value: unknown): value is SingleValue<Option> =>
Is that normal ?

2023-12-15 13:44 UTC, cini9 commented on front/components/publish.tsx
> +  const isSingleValue = (value: unknown): value is SingleValue<Option> =>
It is, I figured unknown was more appropriate than any

2023-12-19 13:03 UTC, merged