Feature/test prod rights
Wavemind/medal-creator pull request #245
Opened 2023-12-15 13:01 UTC by ManuBarchich

2023-12-15 15:48 UTC, frescoal approved these changes

2023-12-19 15:54 UTC, cini9 approved these changes

2024-01-15 07:56 UTC, quentingirard requested changes

2024-01-15 07:56 UTC, quentingirard commented on api/spec/graphql/mutations/decision_trees/create_decision_tree_spec.rb
> +        it 'returns error when algorithm is in prod status', focus: true do
remove focus

2024-01-15 14:42 UTC, merged