Feature/project show
Wavemind/medal-creator pull request #30
Opened 2022-10-14 11:25 UTC by cini9

2022-10-14 14:15 UTC, quentingirard requested changes

2022-10-14 14:15 UTC, quentingirard commented on front/components/sidebar.js
> +          // TODO get the name of the project dynamically and interpolate
enlever todo non ?

2022-10-14 14:15 UTC, quentingirard commented on front/components/table/pagination.js
> +          {[1, 2, 3, 4, 5, 10].map(pageSize => (
rajouer todo pour le faire plus tard

2022-10-14 14:15 UTC, quentingirard commented on front/pages/projects/[name].js
> +        buttonLabel='Open decision tree'
trad

2022-10-17 07:55 UTC, cini9 commented on front/components/sidebar.js
> +          // TODO get the name of the project dynamically and interpolate
Je crois pas encore. Le nom du projet va changer dynamiquement

2022-10-17 09:30 UTC, merged