Feature/graphql pagination
Wavemind/medal-creator pull request #37
Opened 2022-11-01 12:37 UTC by cini9

2022-11-01 17:29 UTC, qtn-g reviewed
Ajouter des tests

2022-11-01 17:29 UTC, quentingirard commented on front/lib/services/modules/algorithm/getAlgorithms.js
> +      let numberText = ''
voir pour optimiser

2022-11-30 12:20 UTC, ManuBarchich requested changes

2022-11-30 12:20 UTC, ManuBarchich commented on api/app/graphql/queries/algorithms/get_algorithms.rb
> +      def authorized?(project_id:, search_term: "")
Pas besoin d'ajouter le paramètre si tu ne l'utilises pas sauf erreur

2022-11-30 12:20 UTC, ManuBarchich commented on api/app/graphql/queries/algorithms/get_algorithms.rb
> +          project.algorithms.ransack("name_cont": search_term).result
op ternaire

2022-11-30 12:20 UTC, ManuBarchich commented on api/app/graphql/queries/projects/get_project_summary.rb
> +module Queries
Regrouper GetProject et GetProjectSummary => ne changer que la requête front pour recevoir uniquement ce qui est nécessaire

2022-11-30 12:20 UTC, ManuBarchich commented on api/app/graphql/types/base_connection.rb
> +      object.items&.count
Pourquoi le & ?

2022-11-30 13:13 UTC, quentingirard approved these changes

2022-11-30 13:13 UTC, quentingirard commented on front/lib/utils/calculatePaginationNumberText.js
> +export default function calculatePaginationNumberText(props) {
enlever le nom de la fonction

2022-11-30 13:19 UTC, merged