Feature/create project
Wavemind/medal-creator pull request #39
Opened 2022-11-09 15:06 UTC by quentingirard

2022-11-09 16:09 UTC, frescoal requested changes

2022-11-09 16:09 UTC, frescoal commented on api/app/graphql/mutations/projects/update_project.rb
> +        raise GraphQL::ExecutionError, "You do not have access to this project"
Hey faut une trad

2022-11-09 16:09 UTC, frescoal commented on api/app/graphql/mutations/projects/create_project.rb
> +        raise GraphQL::ExecutionError, 'You cannot create projects.'
Hey faut une trad

2022-11-09 16:09 UTC, frescoal commented on api/app/graphql/mutations/projects/update_project.rb
> +          GraphQL::ExecutionError.new("Invalid attributes for #{e.record.class}:"\
Hey faut une trad

2022-11-09 16:09 UTC, frescoal commented on api/app/graphql/queries/languages/get_languages.rb
> +        GraphQL::ExecutionError.new("Invalid attributes for #{e.record.class}:"\
Hey faut une trad

2022-11-09 16:09 UTC, frescoal commented on api/app/graphql/queries/projects/get_project.rb
>        # def authorized?(id:)
why is it commented ?

2022-11-09 16:09 UTC, frescoal commented on api/app/graphql/queries/projects/get_projects.rb
>          GraphQL::ExecutionError.new("Invalid attributes for #{e.record.class}:"\
Hey faut une trad

2022-11-09 16:09 UTC, frescoal commented on api/app/graphql/queries/users/get_users.rb
> +        GraphQL::ExecutionError.new("Invalid attributes for #{e.record.class}:"\
Est-ce qu'il y a un moyen de centraliser tous les rescues dans la methode resolve du parrent ou qq ch comme ça ?

2022-11-09 16:09 UTC, frescoal commented on api/app/graphql/types/input/algorithm_input_type.rb
> +      argument :name, String, required: false
Est-ce que le required false est obligatoire pour tous les champs y a pas un autre moyen ?

2022-11-09 16:09 UTC, frescoal commented on api/app/graphql/types/input/node_input_type.rb
> +end
empty line my friend

2022-11-09 16:09 UTC, frescoal commented on api/app/graphql/types/input/project_input_type.rb
> +      argument :village_json, GraphQL::Types::JSON, required: false
Can we remove this as its sent as file ?

2022-11-09 16:09 UTC, frescoal commented on api/app/graphql/types/input/project_input_type.rb
> +      argument :medal_r_config, GraphQL::Types::JSON, required: false
Le medal-R config va pas être envoyer par le front  non ?

2022-11-09 16:09 UTC, frescoal commented on api/app/models/node.rb
> +  has_many :files, as: :fileable, class_name: 'File'
On a vraiment besoin du class name ?

2022-11-09 16:09 UTC, frescoal commented on api/config/locales/fr.yml
> +    attributes:
Comme dis machin : "Heey heyy faut faire les trad des attributs"

2022-11-09 16:09 UTC, frescoal commented on api/spec/graphql/mutations/projects/create_project_spec.rb
> +      end
On test pas l'upload de fichier

2022-11-09 16:09 UTC, frescoal commented on api/spec/graphql/mutations/projects/update_project_spec.rb
> +            updateProject(input: {params: {id: #{@project.id}, name: "Updated project name"}}) {
Il faudrait tester les autres champs pas que le name

2022-11-09 16:09 UTC, frescoal commented on api/spec/graphql/queries/projects/get_project_spec.rb
> +
Looks like something is missing here

2022-11-09 16:09 UTC, frescoal commented on api/spec/graphql/queries/languages/get_languages_spec.rb
> +      query = <<-GRAPHQL
Mettre query dans une fonction comme pour les autres tests

2022-11-09 16:09 UTC, frescoal commented on api/spec/graphql/queries/projects/get_projects_spec.rb
> +
Something missing here

2022-11-09 16:09 UTC, frescoal commented on api/spec/graphql/queries/users/get_users_spec.rb
> +      query = <<-GRAPHQL
fonction query

2022-11-09 16:09 UTC, frescoal commented on api/spec/spec_helper.rb
> +    # DatabaseCleaner.clean_with(:truncation)
Pourquoi c'est commenté ?

2022-11-09 16:09 UTC, frescoal commented on front/components/inputs/richText.js
> +  loading: () => <p>Loading ...</p>,
:poodle:

2022-11-09 16:09 UTC, frescoal commented on front/lib/services/modules/project/createProject.js
> +          $emergencyContentTranslations: HstoreInput!
study desc

2022-11-09 16:09 UTC, frescoal commented on front/pages/_app.js
> +import 'react-quill/dist/quill.snow.css'
move it

2022-11-10 09:55 UTC, cini9 requested changes

2022-11-10 09:55 UTC, cini9 commented on api/app/controllers/graphql_controller.rb
> +      current_api_v1_user: current_api_v1_user || User.first # TODO: remove
Why do we need the || User.first ?

2022-11-10 09:55 UTC, cini9 commented on api/app/graphql/mutations/projects/create_project.rb
> +      def authorized?(params:, villages: nil)
When is this method called ?

2022-11-10 09:55 UTC, cini9 commented on api/app/graphql/mutations/projects/create_project.rb
> +        project_params = Hash params
Pourquoi on doit faire ca ? On peut pas juste utiliser params ?

2022-11-10 09:55 UTC, cini9 commented on api/spec/graphql/mutations/projects/create_project_spec.rb
> +        @first_user = User.create!(first_name: 'Manu', last_name: 'Girard', email: 'manu.girard@wavemind.ch',
Tu utilises @first_user quelque part dans le test ?

2022-11-10 09:55 UTC, cini9 commented on api/spec/graphql/queries/languages/get_languages_spec.rb
> +    it 'returns every users' do
Corriger le "it". Il me semble que ca return les languages et pas les users non ?

2022-11-10 09:55 UTC, cini9 commented on api/spec/spec_helper.rb
> +    User.create(first_name: 'Foo', last_name: 'Bar', email: 'foo.bar@ilovetestunit.com', password: '123456', password_confirmation: '123456', role: 'admin')
Pourquoi on crée un User ici ?

2022-11-11 14:20 UTC, merged