Crud decision tree
Wavemind/medal-creator pull request #69
Opened 2023-02-03 16:41 UTC by ManuBarchich

2023-02-06 08:10 UTC, quentingirard requested changes
Add destroy test

2023-02-06 08:10 UTC, quentingirard commented on api/app/graphql/mutations/decision_trees/create_decision_tree.rb
> +          if decision_tree.save
Tu as déjà fait la validation custom pour les hstores ?

2023-02-06 09:21 UTC, cini9 requested changes

2023-02-06 09:21 UTC, cini9 commented on api/app/graphql/mutations/decision_trees/destroy_decision_tree.rb
> +        { id: id }
T'es obligé de retourner quelque chose ? Un 200 ne suffit pas ?

2023-02-08 09:26 UTC, cini9 approved these changes

2023-02-08 09:33 UTC, merged