Feature/setup 2fa again
Wavemind/medal-creator pull request #79
Opened 2023-03-03 16:35 UTC by quentingirard

2023-03-06 09:37 UTC, qtn-g commented on api/app/controllers/api/v1/overrides/sessions_controller.rb
> +      # added this IF-block
remplacer le commentaire par "# Does user have 2FA activated"

2023-03-06 09:37 UTC, qtn-g commented on api/app/graphql/mutations/two_factor/disable_2fa.rb
> +            puts "****************************************************"
💩

2023-03-06 09:37 UTC, qtn-g commented on api/app/graphql/mutations/two_factor/enable_2fa.rb
> +              puts '****************************************************'
💩

2023-03-06 09:37 UTC, qtn-g commented on api/app/graphql/queries/two_factor/get_qr_code_uri.rb
> +        return true if context[:current_api_v1_user].admin? || context[:current_api_v1_user].id == user_id.to_i
pas besoin que le user soit admin

2023-03-06 09:37 UTC, qtn-g commented on api/app/graphql/queries/two_factor/get_otp_required_for_login.rb
> +        return true if context[:current_api_v1_user].admin? || context[:current_api_v1_user].id == user_id.to_i
pas besoin que le user soit admin

2023-03-06 09:37 UTC, qtn-g commented on api/app/graphql/mutations/two_factor/enable_2fa.rb
> +        return true if context[:current_api_v1_user].admin? || context[:current_api_v1_user].id == user_id.to_i
pas besoin que le user soit admin

2023-03-06 09:37 UTC, quentingirard commented on api/app/graphql/mutations/two_factor/disable_2fa.rb
> +        return true if context[:current_api_v1_user].admin? || context[:current_api_v1_user].id == user_id.to_i
pas besoin que le user soit admin

2023-03-06 09:37 UTC, quentingirard commented on front/components/forms/signIn.tsx
> +      email: 'dev-admin@wavemind.ch',
remove

2023-03-06 09:37 UTC, quentingirard commented on front/components/forms/signIn.tsx
> +          {/* <Box mt={6} textAlign='center'>
remove

2023-03-06 09:37 UTC, quentingirard commented on front/components/sidebar/index.tsx
> +  const handleSignOut = () => false
fix it

2023-03-06 09:37 UTC, quentingirard commented on front/components/twoFactor.tsx
> +        <Text>An error has occured</Text>
trad et voir pour faire qqch de générique. On va utiliser ça à plusieurs endroits

2023-03-06 09:37 UTC, quentingirard commented on front/components/userMenu.tsx
> +    dispatch(apiGraphql.util.resetApiState())
pas nécessaire les dispatch

2023-03-06 09:37 UTC, quentingirard commented on front/components/userMenu.tsx
> +        {session.status !== 'loading' &&
improve

2023-03-06 09:37 UTC, quentingirard commented on front/lib/layouts/default.tsx
> -import { useDeleteSessionMutation } from '@/lib/services/modules/session'
Vérifier que ce module a bien été supprimé

2023-03-06 09:37 UTC, quentingirard commented on front/lib/services/modules/session.ts
> -  SessionLogout,
Vérifier si les types sont utilisés à d'autre endroit

2023-03-06 09:37 UTC, quentingirard commented on front/lib/services/modules/twoFactor.ts
> +    enable2fa: build.mutation({
manque les types

2023-03-06 09:37 UTC, quentingirard commented on front/lib/services/modules/twoFactor.ts
> +    disable2fa: build.mutation({
same

2023-03-06 09:37 UTC, quentingirard commented on front/lib/utils/prepareHeaders.ts
>    { getState }: { getState: () => any }
set as unknown instead of any

2023-03-06 09:37 UTC, quentingirard commented on front/middleware.ts
> +      // TODO ADD LOGIC PATH
make it work

2023-03-06 09:37 UTC, quentingirard commented on front/pages/account/information.tsx
> +import { getServerSession } from 'next-auth'
bouger l'import

2023-03-06 09:37 UTC, quentingirard commented on front/pages/account/projects.tsx
> +        const currentUser = await getServerSession(req, res, authOptions)
Est-ce qu'on arrive pas à mettre ça dans le _app et le transmettre plus bas ?

2023-03-06 09:37 UTC, quentingirard commented on front/pages/api/auth/[...nextauth].ts
> +      // TODO : Maybe call the backend to tell them to sign the user out of devise ?
Do it

2023-03-06 09:37 UTC, quentingirard commented on front/pages/auth/sign-in.tsx
> +      email: 'dev-admin@wavemind.ch',
remove

2023-03-06 09:37 UTC, quentingirard commented on front/pages/auth/sign-in.tsx
> +    if (result) {
improve it

2023-03-06 09:37 UTC, quentingirard commented on front/pages/index.tsx
> +          {projects?.edges.map(project => (
improve it with isSuccess

2023-03-06 09:37 UTC, quentingirard commented on front/pages/projects/[projectId]/algorithms/[algorithmId]/index.tsx
> +          const canCrud = ['admin', 'clinician'].includes(currentUser.user.role)
remove it and calculate it in _app

2023-03-06 09:37 UTC, quentingirard commented on front/pages/projects/[projectId]/algorithms/index.tsx
> +          await Promise.all(
inutile de la mettre là, le déplacer à la dernière requête

2023-03-06 09:37 UTC, quentingirard commented on front/pages/projects/[projectId]/algorithms/index.tsx
> +              userCanEdit: ['admin', 'clinician'].includes(
déplacer dans _app

2023-03-06 09:37 UTC, quentingirard commented on front/pages/projects/[projectId]/algorithms/index.tsx
> +import { GetServerSidePropsContext } from 'next'
déplacer l'import ou le supprimer si pas utilisé

2023-03-06 11:59 UTC, ManuBarchich commented on api/app/graphql/mutations/two_factor/disable_2fa.rb
> +            puts "****************************************************"
:hankey:

2023-03-06 15:52 UTC, cini9 requested changes

2023-03-06 15:52 UTC, cini9 commented on api/app/graphql/types/two_factor_type.rb
> +  class TwoFactorType < Types::BaseObject
Ce sont des champs de User. Est-ce qu'on les ajoute a UserType ou on les laisse separé ?

2023-03-06 15:52 UTC, cini9 commented on api/app/graphql/types/user_type.rb
> +    field :otp_provisioning_uri, String
A enlever d'ici si on garde dans un type separé

2023-03-06 15:52 UTC, cini9 commented on front/components/userMenu.tsx
> +  // TODO : Make call to backend to inform it of the sign out
Should we ?

2023-03-06 15:52 UTC, cini9 commented on front/pages/_app.tsx
> +export type AppPropsWithLayout = AppProps & {
Do we need to export it ? Is it used elsewhere ?

2023-03-06 15:52 UTC, cini9 commented on front/pages/api/auth/[...nextauth].ts
> +          throw new Error(
Est-ce qu'on devrait vraiment passer par une "erreur" pour ca ?

2023-03-06 15:52 UTC, cini9 commented on front/pages/auth/sign-in.tsx
> +        dispatch(apiGraphql.util.resetApiState())
enlever les dispatch ici aussi ?

2023-03-06 15:52 UTC, cini9 commented on front/pages/projects/new.tsx
> +          if (currentUser.user.role !== 'admin') {
Maybe do these checks in the middleware ?

2023-03-06 15:52 UTC, cini9 commented on front/pages/users.tsx
> +          if (currentUser.user.role !== 'admin') {
Maybe do these checks in the middleware ?

2023-03-06 15:52 UTC, cini9 commented on front/types/page.d.ts
> +export type NextPageWithLayout<P = object, IP = P> = NextPage<P, IP> & {
Donner des vrais noms aux variables pour qu'on puisse savoir ce qu'on traite

2023-03-07 10:07 UTC, cini9 approved these changes

2023-03-07 10:07 UTC, cini9 commented on front/lib/services/apiGraphql.ts
> +import { prepareHeaders } from '../utils/prepareHeaders'
@/lib/...

2023-03-07 13:01 UTC, closed without merging