Feature/integrate tables
Wavemind/medal-creator pull request #8
Opened 2022-07-29 13:22 UTC by cini9

2022-08-02 06:40 UTC, quentingirard requested changes

2022-08-02 06:40 UTC, quentingirard commented on front/components/autocomplete/index.js
> +/**
pas mieux de l'appelé AutoCompleteWrapper ou AutoCompleteResult ?

2022-08-02 06:40 UTC, quentingirard commented on front/components/table/index.js
> +
Add comments

2022-08-02 06:40 UTC, quentingirard commented on front/components/table/expandedRow.js
> +  const handleButtonClick = info => {
Add comments and TODO

2022-08-02 06:40 UTC, quentingirard commented on front/components/autocomplete/index.js
> +  const results = useMemo(() => {
Add comments

2022-08-02 06:40 UTC, quentingirard commented on front/components/table/toolbar.js
> +  const { t } = useTranslation('datatable')
Add comments

2022-08-02 06:40 UTC, quentingirard commented on front/public/locales/fr/datatable.json
> +{
en français... ^^

2022-08-02 06:40 UTC, quentingirard commented on front/theme/foundations/colors.js
> +    white: '#FFFFFF',
le white est dispo de base dans chakra. Pas besoin de le spécifier normalement

2022-08-02 06:40 UTC, quentingirard commented on front/utils/buildTableColumns.js
> +  t
Pourquoi pas "t" ? Tu peux l'importer via i18n

2022-08-02 06:40 UTC, quentingirard commented on front/utils/buildTableColumns.js
> +              <Text fontSize="xs">Show decision trees</Text>
trad ou todo pour récupérer la valeur passé en paramètre

2022-09-22 12:25 UTC, cini9 commented on front/utils/buildTableColumns.js
> +  t
Je ne suis pas dans un react component. Du coup je peux pas utiliser le useTranslate hook

2022-09-22 12:37 UTC, merged