Get variables and specs
Wavemind/medal-creator pull request #99
Opened 2023-04-05 08:56 UTC by ManuBarchich

2023-04-05 13:59 UTC, quentingirard requested changes

2023-04-05 13:59 UTC, quentingirard commented on api/app/controllers/graphql_controller.rb
> +  # Handle questions in form data, JSON body, or a blank value
💩

2023-04-05 13:59 UTC, quentingirard commented on api/app/controllers/graphql_controller.rb
> +      variables_param.to_unsafe_hash # GraphQL-Ruby will validate name and type of incoming questions.
💩

2023-04-05 13:59 UTC, quentingirard commented on api/app/graphql/queries/nodes/get_questions.rb
> +    class GetQuestions < Queries::BaseQuery
rename en variables

2023-04-05 13:59 UTC, quentingirard commented on api/spec/graphql/queries/nodes/get_questions_spec.rb
> +        it 'returns algorithms with the name matching search term' do
mauvais commentaire

2023-04-05 13:59 UTC, quentingirard commented on api/app/models/question.rb
> +  def self.search(term, language)
pas nécessaire vu qu'il hérite de node

2023-04-05 13:59 UTC, quentingirard commented on api/app/models/node.rb
> +
espace de trop

2023-04-11 15:59 UTC, ManuBarchich commented on api/app/models/question.rb
> +  def self.search(term, language)
Pour avoir des filtres différents selon si c'est une variable, une drug, un diagnosis, ...

2023-04-12 06:34 UTC, quentingirard requested changes

2023-04-12 06:34 UTC, qtn-g commented on api/app/graphql/types/project_type.rb
> +    def variables_count
@cini9 si t'as 5 pour corriger dans le front c'est volontiers

2023-04-12 06:34 UTC, qtn-g commented on api/app/models/questions_sequence.rb
>  class QuestionsSequence < Node
variablesSequence du coup ?

2023-04-12 06:34 UTC, qtn-g commented on api/app/models/variables/answerable_basic_measurement.rb
> +# Category of variableto complement basic measurements variables
variable to

2023-04-12 06:34 UTC, qtn-g commented on api/app/models/variables/assessment_test.rb
> +# Category of variablefor the medical tests
variable for

2023-04-12 06:34 UTC, qtn-g commented on api/app/models/variables/background_calculation.rb
> +# Category of variablefor the calculate results from a formula and previous answers
same sur les autres models

2023-04-12 06:34 UTC, qtn-g commented on api/app/models/variables/treatment_question.rb
> +
espace en trop

2023-04-12 06:34 UTC, quentingirard commented on api/app/models/variables/treatment_question.rb
> +class Variables::TreatmentQuestion < Variable
treatment variable ?

2023-04-12 06:34 UTC, qtn-g commented on api/app/models/variables/unique_triage_question.rb
> +class Variables::UniqueTriageQuestion < Variable
unique_triage_variable ?

2023-04-12 06:34 UTC, quentingirard commented on api/db/seeds.rb
> +      new_question = Variable.create!(
new_variable

2023-04-12 07:48 UTC, frescoal requested changes

2023-04-12 07:48 UTC, frescoal commented on api/app/models/node.rb
> +
:+1

2023-04-12 07:48 UTC, frescoal commented on api/app/models/questions_sequence.rb
> +  # Return a hash with all variables sequence categories with their name, label and prefix
Heu non

2023-04-12 07:48 UTC, frescoal commented on api/app/models/variables/unique_triage_question.rb
> +class Variables::UniqueTriageQuestion < Variable
No

2023-04-12 07:48 UTC, frescoal commented on api/spec/factories/nodes.rb
> +    answer_type { AnswerType.first }
Est-ce qu'on devrait pas avoir des données de test plus varié ?

2023-04-12 11:45 UTC, merged